thesis02/config/routes.rb
Rails.application.routes.draw do

  resources :cocktails

  resources :maindishes

  resources :dishes
  devise_for :admins
  devise_for :users
  get 'catering/home'
  get 'catering/menu'
  get 'catering/amenities'
  get 'catering/gallery'
  get 'catering/about'
  get 'catering/contact'
  get 'catering/packedmeal'
  get 'catering/cocktail'
  get 'catering/modal'

  resources :catering

  root 'catering#home'

end

thesis02/app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

thesis02/app/models/catering.rb
class Catering < ActiveRecord::Base
end

thesis02/app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
end

thesis02/app/models/dish.rb
class Dish < ActiveRecord::Base
  belongs_to :menu
  belongs_to :dishtype
end

thesis02/app/models/maindish.rb
class Maindish < ActiveRecord::Base
end

thesis02/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

thesis02/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

thesis02/app/controllers/catering_controller.rb
class CateringController < ApplicationController
  def home
  end
end

thesis02/app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  # GET /cocktails
  # GET /cocktails.json
  def index
    @cocktails = Cocktail.all
  end

  # GET /cocktails/1
  # GET /cocktails/1.json
  def show
  end

  # GET /cocktails/new
  def new
    @cocktail = Cocktail.new
  end

  # GET /cocktails/1/edit
  def edit
  end

  # POST /cocktails
  # POST /cocktails.json
  def create
    @cocktail = Cocktail.new(cocktail_params)

    respond_to do |format|
      if @cocktail.save
        format.html { redirect_to @cocktail, notice: 'Cocktail was successfully created.' }
        format.json { render :show, status: :created, location: @cocktail }
      else
        format.html { render :new }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cocktails/1
  # PATCH/PUT /cocktails/1.json
  def update
    respond_to do |format|
      if @cocktail.update(cocktail_params)
        format.html { redirect_to @cocktail, notice: 'Cocktail was successfully updated.' }
        format.json { render :show, status: :ok, location: @cocktail }
      else
        format.html { render :edit }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cocktails/1
  # DELETE /cocktails/1.json
  def destroy
    @cocktail.destroy
    respond_to do |format|
      format.html { redirect_to cocktails_url, notice: 'Cocktail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cocktail
      @cocktail = Cocktail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cocktail_params
      params.require(:cocktail).permit(:name, :price)
    end
end

thesis02/app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: [:show, :edit, :update, :destroy]

  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = Dish.all
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes
  # POST /dishes.json
  def create
    @dish = Dish.new(dish_params)

    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Dish was successfully created.' }
        format.json { render :show, status: :created, location: @dish }
      else
        format.html { render :new }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dishes/1
  # PATCH/PUT /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to @dish, notice: 'Dish was successfully updated.' }
        format.json { render :show, status: :ok, location: @dish }
      else
        format.html { render :edit }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish.destroy
    respond_to do |format|
      format.html { redirect_to dishes_url, notice: 'Dish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dish_params
      params.require(:dish).permit(:name, :price, :menu_id, :dishtype_id)
    end
end

thesis02/app/controllers/maindishes_controller.rb
class MaindishesController < ApplicationController
  before_action :set_maindish, only: [:show, :edit, :update, :destroy]

  # GET /maindishes
  # GET /maindishes.json
  def index
    @maindishes = Maindish.all
  end

  # GET /maindishes/1
  # GET /maindishes/1.json
  def show
  end

  # GET /maindishes/new
  def new
    @maindish = Maindish.new
  end

  # GET /maindishes/1/edit
  def edit
  end

  # POST /maindishes
  # POST /maindishes.json
  def create
    @maindish = Maindish.new(maindish_params)

    respond_to do |format|
      if @maindish.save
        format.html { redirect_to @maindish, notice: 'Maindish was successfully created.' }
        format.json { render :show, status: :created, location: @maindish }
      else
        format.html { render :new }
        format.json { render json: @maindish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maindishes/1
  # PATCH/PUT /maindishes/1.json
  def update
    respond_to do |format|
      if @maindish.update(maindish_params)
        format.html { redirect_to @maindish, notice: 'Maindish was successfully updated.' }
        format.json { render :show, status: :ok, location: @maindish }
      else
        format.html { render :edit }
        format.json { render json: @maindish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maindishes/1
  # DELETE /maindishes/1.json
  def destroy
    @maindish.destroy
    respond_to do |format|
      format.html { redirect_to maindishes_url, notice: 'Maindish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maindish
      @maindish = Maindish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def maindish_params
      params.require(:maindish).permit(:name, :price)
    end
end

thesis02/app/helpers/application_helper.rb
module ApplicationHelper
end

thesis02/app/helpers/catering_helper.rb
module CateringHelper
end

thesis02/app/helpers/cocktails_helper.rb
module CocktailsHelper
end

thesis02/app/helpers/dishes_helper.rb
module DishesHelper
end

thesis02/app/helpers/maindishes_helper.rb
module MaindishesHelper
end

thesis02/app/views/catering/home.html.erb
<div class="container">
    <div class="col-md-12 content1">
        <div class="carousel slide" id="samplecarousel" data-ride="carousel">
          <div class="carousel-inner center-block inner">
            <div class="item active">
              <img src="/assets/carousel images/caswedding.jpg" />
            </div>
            <div class="item">
              <img src="/assets/carousel images/casadding.jpg" />
            </div>
            <div class="item">
              <img src="/assets/carousel images/casfiesta.jpg" />
            </div>
            <div class="item">
              <img src="/assets/carousel images/casparty.jpg" />
            </div>
            <div class="item">
              <img src="/assets/carousel images/cassocial_function.jpg"/>
            </div>
          </div>

        </div>
    </div>
      <div class="col-md-10 col-md-offset-1 content2">
        <div class="row">
          <div class="col-md-3">
            <img src="/assets/human1.png" class="port"/>
          </div>
          <div class="col-md-6">
            <p class="para">
              Lorem ipsum dolor sit amet, consectetur adipisicing elit.
              Assumenda dolore ducimus magnam nisi quibusdam rem ut? Animi,
              beatae, consectetur dolorum ducimus exercitationem id ipsam molestias
              porro sequi tenetur veniam voluptatem!Lorem ipsum dolor sit amet, consectetur adipisicing elit.
              Assumenda dolore ducimus magnam nisi quibusdam rem ut? Animi,
              beatae, consectetur dolorum ducimus exercitationem id ipsam molestias
              porro sequi tenetur veniam voluptatem!
            </p>
          </div>
          <div class="col-md-3">
            <img src="/assets/lechon2.png" class="lechon"/>
          </div>
        </div>
        <hr style="border-color: #1f2124; width: 100%;"/>
        <h3>Catering Services</h3>
        <br/>
        <div class="row picture">
          <div class="col-md-3">
            <a href="#" class="thumbnail">
              <img src="/assets/party.jpg" class="oct"/>
            </a>
          </div>
          <div class="col-md-3">
            <a href="#" class="thumbnail">
              <img src="/assets/fiesta.jpg" class="oct"/>
            </a>
          </div>
          <div class="col-md-3">
            <a href="#" class="thumbnail">
              <img src="/assets/adding.jpg" class="oct"/>
            </a>
          </div>
          <div class="col-md-3">
            <a href="#" class="thumbnail">
              <img src="/assets/wedding.jpg" class="oct"/>
            </a>
          </div>
        </div>
        <div class="container">
          <div class="row service">
            <div class="col-md-3 ">
              <h4>Buffet Type</h4>
              <hr/>
              <h5>P230 / person</h5>
              <ul class="buffet">
                <li>5 Main Dishes</li>
                <li>1 Dessert</li>
                <li>1 Appetizer</li>
                <li>1 Round Softdrink</li>
                <li>Rice</li>
                <li>Purified Water</li>
              </ul>
            </div>
            <div class="col-md-3" >
              <h4>Packed Meal</h4>
              <hr/>
              <h6>Packed in a styrofoam, spoon, fork, and toothpick included.</h6>
              <ul class="packed">
                <li><h5>P130 / Person</h5></li>
                <li><h5>P120 / Person</h5></li>
                <li><h5>P110 / Person</h5></li>
              </ul>
            </div>
            <div class="col-md-3">
              <h4>Cocktail Type</h4>
              <hr/>
              <ul class="cocktail">
                <li><h5> P190 / Person</h5></li>
                <li><h5>P170 / Person</h5></li>
              </ul>
            </div>
            <div class="col-md-3">
              <h4>Our Amenities</h4>
              <hr/>
              <ul class="amenities">
                <li>Buffet Tent</li>
                <li>Tables and Chairs</li>
                <li>Skirted buffet table with centerpiece</li>
                <li>Uniformed Waiters</li>
              </ul>
            </div>
          </div>
          <div class="container ">
            <div class="row buttons">
              <div class="col-md-3">
                <%= link_to 'View Menu', dishes_path, class: 'btn btn-warning center-block' %>
              </div>
              <div class="col-md-3">
                <%= link_to 'View Menu', maindishes_path, class: 'btn btn-success center-block' %>
              </div>
              <div class="col-md-3">
                <%= link_to 'View Menu', cocktails_path, class: 'btn btn-primary center-block' %>
              </div>
              <div class="col-md-3">
                <%= link_to 'More Info', catering_amenities_path, class: 'btn btn-info center-block' %>
              </div>
            </div>
          </div>
        </div>
      </div>

</div>
<div class="container">
  <div class="col-md-10 col-md-offset-1">
    <div class="col-md-4">
      <img src="/assets/logo.png" alt=#" class="ftleft"/>
    </div>
    <div class="col-md-4 center-block">
      <p class="all"> All rights reserved <br/> Copyright &copy; infinity@yahoo.com  2015</p>
    </div>
    <div class="col-md-4 ">
      <img src="/assets/head.png" alt="#" class="ftright pull-right"/>
    </div>
  </div>
</div>
<script type="text/javascript" src="jquery-1.9.1.js"></script>
<script type="text/javascript" src="bootstrap.js"></script>
<script type="text/javascript">
    $(function(){
        $(".carousel").carousel({
            interval: 2000
        });
    });
</script>

thesis02/app/views/catering/modal.html.erb
<h4>Listing Dishes</h4>

<!--<div class="modal fade"-->
<!--id="reserve" tabindex="-1"-->
<!--role="dialog">-->
<!--<div class="modal-dialog">-->
<!--<div class="modal-content">-->
<!--<div class="modal-header">-->
<!--<button class="close" data-dismiss="modal">-->
</button>
<!--<h1>New Reservation</h1>-->
<!--</div>-->
<div class="modal-body">
<form action="#">
<div class="form-group">
<%= link_to  %>
</div>
</form>

</div>
<!--</div>-->
<!--</div>-->
<!--</div>-->

thesis02/app/views/cocktails/edit.html.erb
<h1>Editing Cocktail</h1>

<%= render 'form' %>

<%= link_to 'Show', @cocktail %> |
<%= link_to 'Back', cocktails_path %>

thesis02/app/views/cocktails/new.html.erb
<h1>New Cocktail</h1>

<%= render 'form' %>

<%= link_to 'Back', cocktails_path %>

thesis02/app/views/cocktails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cocktail.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @cocktail.price %>
</p>

<%= link_to 'Edit', edit_cocktail_path(@cocktail) %> |
<%= link_to 'Back', cocktails_path %>

thesis02/app/views/dishes/edit.html.erb
<h1>Editing Dish</h1>

<%= render 'form' %>

<%= link_to 'Show', @dish %> |
<%= link_to 'Back', dishes_path %>

thesis02/app/views/dishes/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container col-md-2">
  <div class="row contentmenu">
    <div class="col-md-10">
      <div class="tab-pane">
        <div class="col-md-2">
          <ul class="nav nav-pills nav-stacked color">
            <li class="active"><%= link_to 'Buffet Type', dishes_path %></li>
            <li><%= link_to 'Packed Meal', maindishes_path %></li>
            <li><%= link_to 'Cocktail Type', cocktails_path %></li>
          </ul>
        </div>

        <div class="menu_tab_ui_panel">
          <div class="menu_tab_panel">
            <div class="menu_inclusions_row">
              <div class="menu_inclusions_cell">
                <div class="menu_inclusions_col">
                  <div class="menu_inclusions_title_div">
                    <span> Buffet Dishes</span>

                  </div>

                  <div class="menu_inclusions_row">
                    <div class="menu_inclusions_cell">
                      <div class="menu_inclusions_col">
                        <div class="menu_inclusions_short_desc_div">
                          Select your favorite dish...
                        </div>
                        <div class="inclusions_menu_div">
                          <fieldset>
                            <table class="tableheight">
                              <!--<thead>-->
                              <!--<tr>-->
                                <!--<th></th>-->
                                <!--<th>Price</th>-->
                                <!--<th>Menu</th>-->
                                <!--<th>Dishtype</th>-->
                                <!--<th colspan="3"></th>-->
                              <!--</tr>-->
                              <!--</thead>-->
                              <div class="container tableheight">
                              <tbody>
                              <% @dishes.each do |dish| %>
                                  <tr>

                                    <td class="list-group">
                                      <% if user_signed_in? %>
                                      <input type="checkbox" class="dish-list" data-dish-name="<%= dish.name %>" data-id="<%= dish.id %>"/>
                                       <% end %>
                                          &nbsp; <%= dish.name %>
                                      <input type="hidden" value="<%= dish.id %>" id="<%= dish.id %>"/>

                                  </td>
                                    <% if admin_signed_in? %>
                                    <!--<td><%= dish.price %></td>-->
                                    <!--<td><%= dish.menu %></td>-->
                                    <!--<td><%= dish.dishtype %></td>-->
                                    <td>&nbsp;  <%= link_to 'Show', dish %></td>
                                    <td>&nbsp; <%= link_to 'Edit', edit_dish_path(dish) %></td>
                                    <td>&nbsp; <%= link_to 'Destroy', dish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                                    <% end %>
                                  </tr>
                              <% end %>


                              </tbody>
                              </div>
                              <% if admin_signed_in? %>
                              <td>&nbsp; <%= link_to 'New Dish', new_dish_path %></td>
                                  <% end %>
                            </table>

                            <br>





                  <div class="menu_inclusions_row">
                    <div class="menu_inclusions_cell">
                      <div class="panel_hz_divider"></div>
                    </div>
                  </div>
                  <div class="menu_inclusions_row">
                    <div class="menu_inclusions_cell">
                      <div class="panel_hz_divider"></div>
                    </div>
                  </div>

                  <div class="menu_inclusions_row">
                    <div class="menu_inclusions_cell">
                      <div class="menu_inclusions_col">
                        <div class="menu_inclusions_title_div">
                          <span>Amenities</span>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="menu_inclusions_row">
                    <div class="menu_inclusions_cell">
                      <div class="menu_inclusions_col">
                        <div class="inclusions_menu_div">
                          <fieldset>
                            <div id="col1">
                              <ul>
                                <li>One Free Buffet Tent</li>
                                <li>Uniformed Waiters</li>
                              </ul>
                            </div>
                            <div id="col2">
                              <ul>
                                <li>Simple Table Centerpieces</li>
                                <li>Stainless Tray for the Lechon</li>
                              </ul>
                            </div>
                            <div id="col3">
                              <ul>
                                <li>Buffet Set-Up with Centerpieces</li>
                                <li>Guest Tables & Chairs</li>
                              </ul>
                            </div>
                          </fieldset>
                        </div>
                      </div>
                    </div>
                  </div>
                            <div class="menu_inclusions_row">
                            <div class="menu_inclusions_cell">
                            <div class="panel_hz_divider"></div>
                            </div>
                            </div>

                            <div class="menu_inclusions_row">
                            <div class="menu_inclusions_cell">
                            <div class="menu_inclusions_col">
                            <div class="menu_inclusions_title_div">
                            <span>Optional Charges</span>
                            </div>
                            </div>
                            </div>
                            </div>

                            <div class="menu_inclusions_row">
                            <div class="menu_inclusions_cell">
                            <div class="menu_inclusions_col">
                            <div class="inclusions_menu_div">
                            <fieldset>
                            <div id="col1">
                            <ul>
                            <li>Tents for Reception
                            <ul>
                            <li>Red Carpet</li>
                            </ul>
                            </li>
                            <li>Packed Meals</li>
                            <li>Ceiling Decor</li>
                            </ul>
                            </div>
                            <div id="col2">
                            <ul>
                            <li>Food Orders</li>
                            <li>Cocktail Tables</li>
                            <li>Tiffany Cahirs</li>
                            </ul>
                            </div>
                            <div id="col3">
                            <ul>
                            <li>Wine Glasses</li>
                            <li>Floral Arrangements</li>
                            <li>Kid's Table and Chairs</li>
                            </ul>
                            </div>
                            </fieldset>
                            </div>
                              <% if user_signed_in? %>
                            <a href="#MyModal" data-toggle="modal"><button>Reserve</button></a>
                            <div class="modal fade"
                                 id="MyModal" tabindex="1"
                                 role="dialog">
                              <div class="modal-dialog modalbg">
                                <div class="modal-content modalbg">
                                  <div class="modal-header modalbg">
                                    <button class="close" data-dismiss="modal">
                                      &times;
                                    </button>
                                    <h4>Reservation list</h4>
                                  </div>
                                  <div class="modal-body modalbg"">

                                    <div class="menu_inclusions_title_div">
                                      <span> Reserved Dishes</span>

                                    </div>
                                    <br/>
                                    <span class="dish-empty-alert" style="color: red">Dish order is empty.</span>
                                    <div class="dish-cart">

                                    </div>
                                  <div class="form-group">
                                    <label>Venue:</label>
                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" name="city/town"/>
                                  </div>
                                  <br/>
                                  <div class="form-group">

                                    <label>Contact no.:</label>

                                    <input type="text" name="contact"/>

                                  </div>
                                  </div>
                                  <div class="modal-footer">
                                    <input class="btn btn-success" type="button" value="Print Reservation Copy" onclick="PrintElem('#MyModal')" />
                                    <input class="btn btn-danger" type="button" value="Close"  data-dismiss="modal"/>

                                  </div>
                                </div>
                              </div>
                            </div>
                                  <% end %>
                            </div>
                            </div>
                            <!--<div id="submit-btn-col"><input type="submit" value="Reserve" name="btn_submit" /> </div>-->
                          </fieldset>

                        </div>

                      </div>
                    </div>
                  </div>


                  <!--<div class="menu_inclusions_row">-->
                    <!--<div class="menu_inclusions_cell">-->
                      <!--<div class="menu_inclusions_col">-->
                        <!--<div class="menu_inclusions_title_div">-->
                          <!--<span>5 Entr&eacute;e&#8217;s</span>-->
                        <!--</div>-->
                      <!--</div>-->
                    <!--</div>-->
                  <!--</div>-->

                  <!--<div class="menu_inclusions_row">-->
                    <!--<div class="menu_inclusions_cell">-->
                      <!--<div class="menu_inclusions_col">-->
                        <!--<div class="menu_inclusions_short_desc_div">-->
                          <!--Your choice of 5 main dishes from our menu, pork, chicken, fish, beef, noodles, seafoods, vegetables, and others...-->
                        <!--</div>-->
                      <!--</div>-->
                    <!--</div>-->
                  <!--</div>-->
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="col-md-10 col-md-offset-1">
      <div class="col-md-4">
        <img src="/assets/logo.png" alt=#" class="ftleft"/>
      </div>
      <div class="col-md-4 center-block">
        <p class="all"> All rights reserved <br/> Copyright &copy; infinity@yahoo.com  2015</p>
      </div>
      <div class="col-md-4 ">
        <img src="/assets/head.png" alt="#" class="ftright pull-right"/>
      </div>
    </div>
  </div>
</div>
<!--<h1>Listing Dishes</h1>-->

<!--<div class="modal fade"-->
     <!--id="reserve" tabindex="-1"-->
        <!--role="dialog">-->
  <!--<div class="modal-dialog">-->
    <!--<div class="modal-content">-->
      <!--<div class="modal-header">-->
        <!--<button class="close" data-dismiss="modal">-->
          <!--&times;-->
        <!--</button>-->
        <!--<h1>New Reservation</h1>-->
      <!--</div>-->
      <!--<div class="modal-body">-->
        <!--<form action="#">-->
          <!--<div class="form-group">-->

          <!--</div>-->
        <!--</form>-->
      <!--</div>-->
    <!--</div>-->
  <!--</div>-->
<!--</div>-->
<script type="text/javascript">
    var ctr = 0;
    $(".dish-list").on("click", function (){
        var dish_name = $(this).data("dish-name");
        var dish_id = $(this).data("id");
        if(this.checked) {
            var value = "<span style='display: block;' class='dish-order-"+ dish_id +"'>"+ dish_name +"</span>";
            $(".dish-cart").append(value);
            ctr++;
            $(".dish-empty-alert").hide();
        }else {
            $(".dish-order-"+ dish_id).remove();
            ctr--;
            if(ctr == 0) {
                $(".dish-empty-alert").show();
            }
        }
    });
</script>

thesis02/app/views/dishes/new.html.erb
<h1>New Dish</h1>

<%= render 'form' %>

<%= link_to 'Back', dishes_path %>

thesis02/app/views/dishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dish.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @dish.price %>
</p>

<!--<p>-->
  <!--<strong>Menu:</strong>-->
  <!--<%= @dish.menu %>-->
<!--</p>-->

<!--<p>-->
  <!--<strong>Dishtype:</strong>-->
  <!--<%= @dish.dishtype %>-->
<!--</p>-->

<%= link_to 'Edit', edit_dish_path(@dish) %> |
<%= link_to 'Back', dishes_path %>

thesis02/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thesis02</title>
  <link rel="Shortcut Icon" href="/assets/ico.png" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="navbar-header">
    <button class="navbar-toggle" data-toggle="collapse"
            data-target="#NavbarToggle">
      <span class="sr-only">Toggle Navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <div class="navbar-header">
      <a href="#" class="navbar-brand"
         data-toggle="tooltip"
         data-placement="right"
         title="Infinity Online Catering Services!">
        <img src="/assets/logo.png" alt="images" class="logo"/>
      </a>
    </div>
  </div>

  <div class="collapse navbar-collapse" id="NavbarToggle">
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
      <li class="navborder"><%= link_to 'Home', catering_home_path %></li>
      <li class="navborder"><%= link_to 'Menu', dishes_path %></li>
      <li class="navborder"><%= link_to 'Amenities',catering_amenities_path %></li>
      <li class="navborder"><%= link_to 'Gallery', catering_gallery_path %></li>
      <li class="navborder"><%= link_to 'About us', catering_about_path %></li>
      <li class="navborder"><%= link_to 'Contact us', catering_contact_path %></li>
          <ul class="nav navbar-nav navbar-right">
      <li id="fat-menu" class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Account <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><%== link_to current_user.email %></li>
          <li><%= link_to "Profile", edit_user_registration_path %></li>
          <li>
            <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
          </li>

        </ul>
      </li>
      <% else %>
          <li class="pull-right"><%= link_to "Sign in", new_user_session_path %></li>
          <li class="pull-right"><%= link_to "Admin", new_admin_session_path %></li>
      <% end %>
      </ul>
    </ul>

  </div>

</nav>


<%= yield %>



</body>
</html>

thesis02/app/views/maindishes/edit.html.erb
<h1>Editing Maindish</h1>

<%= render 'form' %>

<%= link_to 'Show', @maindish %> |
<%= link_to 'Back', maindishes_path %>

thesis02/app/views/maindishes/new.html.erb
<h1>New Maindish</h1>

<%= render 'form' %>

<%= link_to 'Back', maindishes_path %>

thesis02/app/views/maindishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @maindish.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @maindish.price %>
</p>

<%= link_to 'Edit', edit_maindish_path(@maindish) %> |
<%= link_to 'Back', maindishes_path %>